# Spring 配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# 开发环境配置
server:
  port: 8082

# Mybatis 配置
mybatis-plus:
  type-aliases-package: com.personal.blog.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  # 使用 Mybatis-plus 可直接在配置文件配置，如下方规则设置
  # config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    # 驼峰式命名
    map-underscore-to-camel-case: true
    # 全局映射器启用缓存
    cache-enabled: true
    # 允许 JDBC 支持自动生成主键
    use-generated-keys: true
    # 配置默认的执行器
    default-executor-type: reuse
    # 指定 MyBatis 所用日志的具体实现
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      # 数据库 ID 自增
      id-type: auto
# 日志配置
logging:
  level:
    com.personal: debug
    org.springframework: warn
  config: classpath:logback-spring.xml


