# Spring 配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false

# 开发环境配置
server:
  port: 8082

# Mybatis 配置

# 日志配置
logging:
  level:
    com.personal: debug
    org.springframework: warn
  config: classpath:logback-spring.xml
